### ISSUE TITLE
シミュレーションの内容を英語で説明

### ISSUE THREAD

**Issue by y-yosuke** [y-yosuke/formula-ppoino#16]
して欲しいです，とのことで英語編集用の Issue．ここで編集してHTMLでコピーかな．
英語でメールよりも長い文章書くの久しぶり... orz （そんなに長くないけど）

今週末（〜2016年9月11日）に書き上げる予定．

説明の対象は主に fp-023c - Front Aero Devices
https://www.simscale.com/projects/yosukegb4/fp-023c_-_control/

fp-023b - Front Aero Devices も関係してくるんだけどどの程度絡めるか？
https://www.simscale.com/projects/yosukegb4/fp-023b_control/

酷い英語があったら指摘して頂けるとありがたいです．

**Comment by y-yosuke** [comment]
Editing now...

The Car

This car project is my formula style 2-seater car project published in GitHub.

https://github.com/y-yosuke/formula-ppoino
https://github.com/y-yosuke/ppoino-cars

"fp" are the initials of "formula-ppoino". "-ppoino" is a Japanese expression that means "a thing(s) looks/sounds like -", so "formula-ppoino" means "a car looks like formula".

I designed the car in the style of the early 2000s formula cars.
The reason of "2-seater" is to feel the joy riding in the formula car with friends on the road, it is not only for the competitions in racing circuits.


The model

I designed the car using Rhinoceros.

For importing multiple faces body, front wheels and rear wheels into one geometry, I export ASCII STL files of the each faces from Rhinoceros and edit the names of the solids in these ASCII STL files manually. Then I put these STL files together into the one STL file using "cat" command and upload it.

The size of the mesh is required 9M nodes at least in this case. It was derived from the result of the simulations in "fp-023b Test-C".
https://www.simscale.com/projects/yosukegb4/fp-023b_test-c/



The aim of the simulations

front and rear downforce balance

**Comment by y-yosuke** [comment]
Editing now...

## The aim of the simulations

Generally in the aerodynamic development of the racing cars, you mainly focus on the characteristics below.

- Downforce, Drag, L/D
- Balance of the front and rear downforces
- Sensitivity of the Downforce and Balance to the vehicle ride heights

Through the simulations of ""fp-023b Test-C" https://www.simscale.com/projects/yosukegb4/fp-023b_test-c/", I found the front downforce was not enough. It depends on the car weight balance and how the vehicle ride heights change, but I provisionaly set the goal that the center of the front and rear downforces will be about 60-65%. ( Clf : Clr = 40-35 : 60-65 )

**Comment by emijah** [comment]
Edited

## The aim of the simulations

Generally, during aerodynamic development of racing cars, you mainly focus on the characteristics below.

- Downforce, Drag, L/D
- Balance of the front and rear downforces
- Sensitivity of the Downforce and Balance to the vehicle ride heights

Through simulation, as in ""fp-023b Test-C" https://www.simscale.com/projects/yosukegb4/fp-023b_test-c/", I found there was insufficient front downforce. It depends on the car weight balance and how the vehicle ride heights change, but I provisionaly set the goal to distribute the front and rear downforces to be about 60-65%. ( Clf : Clr = 40-35 : 60-65 )

**Comment by y-yosuke** [comment]
@emijah ありがとうございます！

**Comment by y-yosuke** [comment]
Editing...

Through simulations, as in "fp-023b - Front Aero Devices https://www.simscale.com/projects/yosukegb4/fp-023b_control/ ",

**Comment by emijah** [comment]
@y-yosuke これよりも前の部分は直接投稿した文書を編集してしまったかもしれません。確認しますね。

**Comment by emijah** [comment]
Edited

## The car

This car project is my formula style 2-seater car project published in GitHub.

https://github.com/y-yosuke/formula-ppoino

I designed the car in the style of the early 2000s formula cars. The reason it's a "2-seater" is to allow you to share the joy of riding in a formula car with your friends on the road, it is not only for competition on racing circuits.

The prefix "fp" are the initials of "formula-ppoino". "-ppoino" is a Japanese expression that means "thing(s) looks/sounds/drives like -", so "formula-ppoino" means it "looks like a formula car".


## The model

I designed the car using the modelling software Rhinoceros.

To import multiple faces, the body, front wheels and rear wheels into one geometry, I exported ASCII STL files of each faces from Rhinoceros and edited the names of the solids in these ASCII STL files manually. Then I put these STL files together into the one STL file using "cat" command and uploaded it.

The size of the mesh required is at least 9M nodes in this case. It was derived from the result of the simulations in "fp-023b Test-C".
https://www.simscale.com/projects/yosukegb4/fp-023b_test-c/

**Comment by y-yosuke** [comment]
ちなみに SimScale の中の人から説明を書き加えて下さいというお願いで，
下記フォーラムのページを参考にここまでは全然詳しくなくて大丈夫とのこと．
https://www.simscale.com/forum/t/wind-turbine-blade-fluid-and-structural-optimisation-using-cae/37492

主に私が SimScale に貼った ParaView で Post-process した画像の解説が欲しいそうです．
（それらの説明がそれなりであれば）Project Spotlight として来週あたり紹介するかもとのこと．

**Comment by emijah** [comment]
よかったねぇ！
実際につくラメのスポンサーも募集中と書いてみては？

2016年9月9日 19:02 Yosuke Yamamoto <notifications@github.com>:

**Comment by y-yosuke** [comment]
GitHub のコメントって編集履歴は残らないんでしたっけ？

**Comment by y-yosuke** [comment]
## The result of "fp-023b - Front Aero Devices" (Summary)


- S-Duct
- Front Wing t40/t50 Comparison
- Front Fender Narrow Pillar
- Front Inner Fender Modification
- Front Flap
  - Position X+20mm
  - Angle +7.5deg (mechanical MAX +15deg)


## The result of "fp-023c - Front Aero Devices"

**Comment by y-yosuke** [comment]
Editing...

## fp-023c - Front Aero Devices

**Comment by y-yosuke** [comment]
【 fp-023c - Summary of the Results (Part 2) 】Front Fender Stay (Part 1)

Edited in https://github.com/y-yosuke/formula-ppoino/issues/12#issuecomment-246096612

**Comment by y-yosuke** [comment]
【 fp-023c - Summary of the Results (Part 3) 】Front Fender Stay (Part 2)

Edited in https://github.com/y-yosuke/formula-ppoino/issues/12#issuecomment-246107120

**Comment by y-yosuke** [comment]
後は...

- [ ] S-Duct B の比較
- [ ] Ride height の比較

かな．
渦度に関しては私の工学的な理解が浅いので説明はしないでおこうかと思っている．

**Comment by y-yosuke** [comment]
【 fp-023c - Summary of the Results (Part 4) 】S-Duct B

Edited in https://github.com/y-yosuke/formula-ppoino/issues/12#issuecomment-246163741

**Comment by y-yosuke** [comment]
Front / Rear のダウンフォースの割合は風洞実験の経験から設定した暫定値なので
本シミュレーション上ではそれは Body Only の Coefficients に相当するから "of the body" を入れた方が良い気がする．

> I provisionaly set the goal to distribute the front and rear downforces to be about 60-65%.

I provisionaly set the goal to distribute the front and rear downforces of the body to be about 60-65%.

**Comment by y-yosuke** [comment]
"
Ride Heights Comparison

Ideally, various vehicle ride heights are tested for each aero-devices to know the sensitivity of the downforce and balance to the ride heights. But it needs a lot of 'core hours' to solve.
"

**Comment by y-yosuke** [comment]
【 fp-023c - Summary of the Results (Part 5) 】Front Fender Louver C + Louver Stay B

Edited in https://github.com/y-yosuke/formula-ppoino/issues/12#issuecomment-246167618

**Comment by y-yosuke** [comment]
【 fp-023c - Summary of the Results (Part 6) 】Ride Heights Comparison

Edited in https://github.com/y-yosuke/formula-ppoino/issues/12#issuecomment-246168325

**Comment by y-yosuke** [comment]
私の知識で説明出来るのは大体これら ↑ ぐらいかな．

やはり乱流エネルギー k の図は説明に十分な知識を持ち合わせていないので避けておこう．

**Comment by y-yosuke** [comment]
修正していただいたものをまとめ，あんど，投稿．

## The car

This car project is my formula style 2-seater car project published in GitHub.

https://github.com/y-yosuke/formula-ppoino

I designed the car in the style of the early 2000s formula cars. The reason it's a "2-seater" is to allow you to share the joy of riding in a formula car with your friends on the road, it is not only for competition on racing circuits.

The prefix "fp" are the initials of "formula-ppoino". "-ppoino" is a Japanese expression that means "thing(s) looks/sounds/drives like -", so "formula-ppoino" means it "looks like a formula car".


## The model

I designed the car using the modelling software Rhinoceros.

To import multiple faces, the body, front wheels and rear wheels into one geometry, I exported ASCII STL files of each faces from Rhinoceros and edited the names of the solids in these ASCII STL files manually. Then I put these STL files together into the one STL file using "cat" command and uploaded it.

The size of the mesh required is at least 9M nodes in this case. It was derived from the result of the simulations in "fp-023b Test-C".
https://www.simscale.com/projects/yosukegb4/fp-023b_test-c/


## The aim of the simulations

Generally, during aerodynamic development of racing cars, you mainly focus on the characteristics below.

- Downforce, Drag, L/D
- Balance of the front and rear downforces
- Sensitivity of the Downforce and Balance to the vehicle ride heights

Through simulation, as in ""fp-023b Test-C" https://www.simscale.com/projects/yosukegb4/fp-023b_test-c/", I found there was insufficient front downforce. It depends on the car weight balance and how the vehicle ride heights change, but I provisionaly set the goal to distribute the front and rear downforces of the body to be about 60-65%. ( Clf : Clr = 40-35 : 60-65 )

## The conditions of the simulations
The conditions are in accordance with the state of the car running on public roads.

- Inlet velocity, Moving floor speed : 30 m/s (= 108 km/h)
- Ride height : Front: 110mm / Rear: 110mm (basically)


## The result of "fp-023b - Front Aero Devices" (Summary)

I tested some front aero-devices in the simulations "fp-023b Front Aero Devices https://www.simscale.com/projects/yosukegb4/fp-023b_control/ ". The following front aero-devices increased the front downforce effectively. These decreased the aerodynamical front lift to almost zero, but the ratio of front-rear downforce was still 96% on the rear axle.

- S-Duct at Nose Cone
- Front Wing t50 (changed from t40)
- Modified Front Inner Fender
- Front Flap
  - Position X+20mm
    - Angle +7.5deg (mechanical MAX +15deg)

Coefficients of the Body and Wheels							

Coef.	|	fp-023b Control	|	fp-023c Control	|	Difference	|	Difference %	|	Remarks
---	|	---	|	---	|	---	|	---	|	---
Cm	|	0.1330	|	0.0781	|	-0.0549	|	-41.3	|	
Cd	|	0.5510	|	0.5590	|	+0.0080	|	+1.4	|	
Cl	|	-0.1550	|	-0.1693	|	-0.0142	|	-9.2	|	
Clf	|	0.0555	|	-0.0066	|	-0.0620	|	-111.8	|	
Clr	|	-0.2105	|	-0.1627	|	+0.0478	|	+22.7	|	
CoP	|	1.3579	|	0.9613	|	-0.3966	|	-39.7	|	
L/D	|	-0.2813	|	-0.3028	|	-0.0215	|	-7.6	|	

- fp-023b Control : Base of "fp-023b - Front Aero Devices"
- fp-023c Control : Best result of "fp-023b - Front Aero Devices"

**Comment by y-yosuke** [comment]
各項目題の "The" は外すかな...

**Comment by emijah** [comment]
今日の昼休みにまた見ますね

2016-09-12 10:45 GMT+09:00 Yosuke Yamamoto <notifications@github.com>:

**Comment by y-yosuke** [comment]
ありがとうございます．正午までに整えてまとめておきます．

**Comment by y-yosuke** [comment]
## Front Fender Louvers


## Front Fender Stay (Part 1)


## Front Fender Stay (Part 2)


## S-Duct B


## Front Fender Louver C + Louver Stay B


## Ride Heights Comparison

**Comment by y-yosuke** [comment]
STL モデルのエクスポート・インポートの話は別に重要じゃないかな... とも思うけど，
私の方からは投稿はしておいて，先方で不必要だと思えば転載のときに削ってもらえるでしょう．

**Comment by y-yosuke** [comment]
Conclusion みたいなのもあった方が良いのかな．

**Comment by emijah** [comment]
ルーバーってlouvreって綴りじゃなかったでしたっけ？

**Comment by y-yosuke** [comment]
https://en.wikipedia.org/wiki/Louver
Louver : 米国語
Louvre : 英国語
のようです．レーシングカーでは「英国語」が多い気がしますが，
会社員当時は適当に Louver を使っていたような気がします．

**Comment by y-yosuke** [comment]
"Musée du Louvre" も Louvre か．勉強になるー

**Comment by emijah** [comment]
意図的にLouvreを広めていたつもりだったのですが、違ったか。
Conclusionsを現在進行形にするかどうかですが、今やっている内容でとどめるならば、それでいいんじゃないですかね？

一度まとまったやつをEdited

## Contents

- Car
- Model
- Conditions
- Aim of the simulation
- Summary of simulation "fp-023b - Front Aero Devices"
                       ^^^
- Front Fender Louvers
- Front Fender Stay (Part 1)
- Front Fender Stay (Part 2)
- S-Duct B
- Front Fender Louver C + Louver Stay B
- Ride Heights Comparison
- Conclusions


## Car

This car project is my formula style 2-seater car project published in GitHub.

https://github.com/y-yosuke/formula-ppoino

I designed the car in the style of the early 2000s formula cars. The reason it's a "2-seater" is to allow you to share the joy of riding in a formula car with your friends on the road, it is not only for competition on racing circuits.

The prefix "fp" are the initials of "formula-ppoino". "-ppoino" is a Japanese expression that means "thing(s) looks/sounds/drives like -", so "formula-ppoino" means it "looks like a formula car".


## Model

I designed the car using the modelling software Rhinoceros.

To import multiple faces, the body, front wheels and rear wheels into one geometry, I exported ASCII STL files of each faces from Rhinoceros and edited the names of the solids in these ASCII STL files manually. Then I put these STL files together into the one STL file using "cat" command and uploaded it.

The size of the mesh required is at least 9M nodes in this case. It was derived from the result of the simulations in "fp-023b Test-C".
https://www.simscale.com/projects/yosukegb4/fp-023b_test-c/


## Conditions

The conditions of the simulations are in accordance with the state of the car running on public roads.

- Inlet velocity, Moving floor speed : 30 m/s (= 108 km/h)
- Ride height : Front: 110mm / Rear: 110mm (basically)


## Aim of the simulations

Generally, during aerodynamic development of racing cars, you mainly focus on the characteristics below.

- Downforce, Drag, L/D
- Balance of the front and rear downforces
- Sensitivity of the Downforce and Balance to the vehicle ride heights

Through simulation, as in "fp-023b Test-C https://www.simscale.com/projects/yosukegb4/fp-023b_test-c/ ", 
                                  ^
I found there was insufficient front downforce. It depends on the car weight balance and how the vehicle ride heights change, but I provisionaly set a goal to distribute the front and rear downforces of the body to 
                                                                            ^変わるから
be about 60-65%. ( Clf : Clr = 40-35 : 60-65 )


## Summary of of the simulation "fp-023b - Front Aero Devices"

I tested some front aero-devices in the simulation "fp-023b - Front Aero Devices https://www.simscale.com/projects/yosukegb4/fp-023b_control/ ". The following front aero-devices increased the front downforce effectively. These decreased the aerodynamical front lift to almost zero, but the ratio of front-rear downforce was still 96% on the rear axle.

- S-Duct at Nose Cone
- Front Wing t50 (changed from t40)
- Modified Front Inner Fender
- Front Flap
  - Position X+20mm
    - Angle +7.5deg (mechanical MAX +15deg)

Coefficients of the Body and Wheels							

Coef.	|	fp-023b Control	|	fp-023c Control	|	Difference	|	Difference %	|	Remarks
---	|	---	|	---	|	---	|	---	|	---
Cm	|	0.1330	|	0.0781	|	-0.0549	|	-41.3	|	
Cd	|	0.5510	|	0.5590	|	+0.0080	|	+1.4	|	
Cl	|	-0.1550	|	-0.1693	|	-0.0142	|	-9.2	|	
Clf	|	0.0555	|	-0.0066	|	-0.0620	|	-111.8	|	
Clr	|	-0.2105	|	-0.1627	|	+0.0478	|	+22.7	|	
CoP	|	1.3579	|	0.9613	|	-0.3966	|	-39.7	|	
L/D	|	-0.2813	|	-0.3028	|	-0.0215	|	-7.6	|	

- fp-023b Control : Base of "fp-023b - Front Aero Devices"
- fp-023c Control : Best result of "fp-023b - Front Aero Devices"

**Comment by emijah** [comment]
そうそう。キーワードをlouvre aerodynamicにしないと永久にリファレンスは出てきません

2016-09-12 12:33 GMT+09:00 Yosuke Yamamoto <notifications@github.com>:

**Comment by y-yosuke** [comment]
シミュレーションの結果のまとめ各項目もこっちにコピーしておいた方が良かったですか？

Front Fender Louvers
Content here : #12 (comment)

**Comment by y-yosuke** [comment]
前半の修正点 ^ 理解・了解しました．

**Comment by emijah** [comment]
Edited

## Front Fender Louvres

Content here : https://github.com/y-yosuke/formula-ppoino/issues/12#issuecomment-246084217


## Front Fender Stay (Part 1)

Content here : https://github.com/y-yosuke/formula-ppoino/issues/12#issuecomment-246096612


## Front Fender Stay (Part 2)

Content here : https://github.com/y-yosuke/formula-ppoino/issues/12#issuecomment-246107120


## S-Duct B

Content here : https://github.com/y-yosuke/formula-ppoino/issues/12#issuecomment-246163741


## Front Fender Louvre C + Louvre Stay B

Content here : https://github.com/y-yosuke/formula-ppoino/issues/12#issuecomment-246167618


## Ride Heights Comparison

Content here : https://github.com/y-yosuke/formula-ppoino/issues/12#issuecomment-246168325


## Conclusions

Conclusions or Conclusion ???

Content here : https://github.com/y-yosuke/formula-ppoino/issues/12#issuecomment-246227805

**Comment by emijah** [comment]
動画とか見入っちゃいますね

**Comment by y-yosuke** [comment]
これはリンク先の英語の内容も大丈夫だったということでしょうか？

**Comment by y-yosuke** [comment]
SimScale の forum は基本的には Markdown に対応しているものの Markdown の表には対応していない HTML でないとだめのようだ．

**Comment by emijah** [comment]
リンク先は後で確認します

**Comment by y-yosuke** [comment]
すみません．よろしくお願い致します．

**Comment by y-yosuke** [comment]
HTML でも’表’が表示されないなぁ...

**Comment by y-yosuke** [comment]
表は TeX で書きなはれ，ということなのかな？
https://www.simscale.com/forum/t/mathjax-arrays/444

**Comment by y-yosuke** [comment]
TeX でも表示されない．キャプチャして画像貼りつけかな．

**Comment by y-yosuke** [comment]
Louver / Louvre 問題は既に ParaView キャプチャした画像に Louver で書いてあるので Louver で統一します．

**Comment by y-yosuke** [comment]
もしかしてこれらのドキュメント全体の標題も必要な気がしてきた...
Result of "fp-023c Front Aero Devices" ? Results ???

**Comment by emijah** [comment]
@y-yosuke なにー！(Louvre)

fp-023c - Front Aero Device Study

はどうですか？

**Comment by y-yosuke** [comment]
@emijah すみません (Louvre)

標題はそれにしましょう．

**Comment by y-yosuke** [comment]
アップロード始めました．"Sorry. Now Editing..." を冒頭に書きながら．
追加修正点は私が後から手動修正します．
https://www.simscale.com/forum/t/fp-023c-control-simulation-project-by-yosukegb4/36689/17

**Comment by y-yosuke** [comment]
説明用にアップロードした画像をこちらにも保管しておく．
![fp-023x_rhino-screenshot](https://cloud.githubusercontent.com/assets/3119480/18460992/0cb65d90-79b1-11e6-88a2-5947c909693b.png)

**Comment by y-yosuke** [comment]
（図を多く貼るとボリュームが出て沢山書いたような気分になる）

**Comment by y-yosuke** [comment]
全体の項目の階層を次のようにして投稿済みとしました．
@emijah さん，協力いただき大変ありがとうございました．

### Contents

- Introductions
  - Car
  - Model
  - Conditions
  - Aim of the simulation
  - Summary of simulation "fp-023b - Front Aero Devices"
- Simulations
  - Front Fender Louvers
  - Front Fender Stay (Part 1)
  - Front Fender Stay (Part 2)
  - S-Duct B
  - Front Fender Louver C + Louver Stay B
  - Ride Height Comparison
  - Conclusion

**Comment by y-yosuke** [comment]
（あれもこれも説明しなきゃと思って of とか the とかいろいろと増殖して格好悪い表現になっていく私の英語力... orz）

**Comment by y-yosuke** [comment]
無事に紹介されました．URLもそれらしいものに変えて頂いたようです．
https://www.simscale.com/forum/t/fp-023c-front-aero-device-study/36689

あらためて @emijah さん協力ありがとうございました．

ということで，この Issue は Close します．

**Comment by y-yosuke** [comment]
（そういえば SimScale は OnShape や Autodesk と連携しているから Rhinoceros に関係した記述も編集されずにそのままだったな... ）

**Comment by emijah** [comment]
連携ができているということはツールとしては大きなことですからね。中途半端な支援しかできずもうしわけないです。

**Comment by y-yosuke** [comment]
いえいえ，修正して頂いた点から英語の感覚が少し分って良かったです．

OnShape / Autodesk はテクニカルパートナーなのかな？と勝手に思っていましたが
いらぬ心配だったようです．
