### ISSUE TITLE
ライセンスの変更 CC の BY-SA から BY に変更したい

### ISSUE THREAD

**Issue by y-yosuke** [y-yosuke/formula-ppoino#53]
ソースとしてのコントリビュータとしては @y-yossuke のみなので一義的な権利保有は私1名なのですが，ライセンス変更に異議がある場合は本 Issue に投稿願います．

**Comment by emijah** [comment]
異議なし

**Comment by y-yosuke** [comment]
@emijah ありがとうございます．

**Comment by y-yosuke** [comment]
CC-BY へのライセンス変更の PR & Merge して変更を確認しました．
